### ISSUE TITLE
There is no tutorial or instructions to install Ubuntu touch

### ISSUE THREAD

**Issue by pachof** [areyoudeveloper/ubports-ginkgo#1]
Hello, I have been looking for a port of Ubuntu Touch for Redmi Note 8 that has the focal version for about a month, I found this repository and I don't know how to install this port, if you made a tutorial on how to install this port I would be very grateful

**Comment by areyoudeveloper** [comment]
this is my personal ci but if you realy want you can download img from here https://github.com/areyoudeveloper/ubports-ginkgo/actions/runs/6327171613 flash ubuntu.img to system and boot from usrmerge package to boot partition also you need miui Android 10 vendor and firmware

**Comment by pachof** [comment]
One question, is there a build for the sailfishos-ginkgo repository? To install and use it, it is one of my favorite systems
